let g:jedi#goto_command = "<leader>md"
let g:jedi#goto_assignments_command = "<leader>mg"
let g:jedi#goto_definitions_command = "<leader>me"
let g:jedi#documentation_command = "<leader>mk"
let g:jedi#usages_command = "<leader>mn"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#rename_command = "<leader>mr"

let g:jedi#use_splits_not_buffers = "top"
let g:jedi#show_call_signatures = "2"
